name: Build MAUI-Mac

on:
  push:
    branches: [ main, dev/add-ci ]
    paths:
      - '.github/workflows/dev-mac.yml' 
      - 'src/**'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
    DOTNETVERSION:  6.0.100
    DOTNETROOT: /usr/local/share/dotnet/
    DOTNETTOOLS: ~/.dotnet/tools

jobs:
  buildmac:
    runs-on: macos-11
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Artifacts Folder
        shell: pwsh
        run: mkdir $GITHUB_WORKSPACE\artifacts

      - name: Setup .NET Core SDK 5.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name:  install .NET 6 preview
        shell: bash
        run: |
          export PATH="${{env.DOTNETROOT}}:${{env.DOTNETTOOLS}}:$PATH" &&
          curl -L https://raw.githubusercontent.com/dotnet/install-scripts/7a9d5dcab92cf131fc2d8977052f8c2c2d540e22/src/dotnet-install.sh > dotnet-install.sh &&
          sh dotnet-install.sh --version ${{env.DOTNETVERSION}} --install-dir ${{env.DOTNETROOT}} --verbose &&
          dotnet --list-sdks &&
          echo "$PATH"
          
      - name: Install and Run maui-check Tool
        shell: bash
        run: |
          dotnet tool update --global redth.net.maui.check &&
          maui-check --ci --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --skip edgewebview2
      - name: Build app
        shell: bash
        run: |
          dotnet build src -f net6.0-android &&
          dotnet build src -f net6.0-ios &&
          dotnet build src -f net6.0-maccatalyst

      - name: upload android build to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: maui-cicd
          token: ${{secrets.APP_CENTER_TOKEN}}
          file: src\bin\Release\**\*-Signed.apk
          debug: false
      - name: upload mac build to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: maui-cicd
          token: ${{secrets.APP_CENTER_TOKEN}}
          file: src/bin/Release/net6.0-maccatalyst/maccatalyst-x64/maui-cicd.app/Contents/MacOS/maui-cicd
          debug: false