name: Build MAUI-Windows

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
    DOTNETVERSION:  6.0.100

jobs:
  buildwindows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
          
      - name:  install .NET
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
          & .\dotnet-install.ps1 -Version ${{env.DOTNETVERSION}} -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
          & dotnet --list-sdks


      # temporary fix: run this script to manually patch the vs dlls
      # https://github.com/dotnet/runtime/issues/59619#issuecomment-929007782

#      - name:  patch vs
#       shell: pwsh
#      run: powershell .\build\patch-vs.ps1

      
      - name: Install and Run maui-check Tool
        shell: pwsh
        run: |
          & dotnet tool update --global redth.net.maui.check
          & maui-check --ci --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --skip edgewebview2

      - name: Restore nuget packages
        run: dotnet restore src/maui-cicd.sln

      - name: Build android debug
        shell: pwsh
        run: dotnet build src -f net6.0-android -c Debug

      - name: Build windows debug
        shell: pwsh
        run: dotnet build src -f net6.0-windows10.0.19041 -c Debug

      - name: Build WinUI3 Debug
        run: msbuild src/maui-cicd.sln -restore -p:Configuration=Debug

      - name: Build WinUI3 Release
        run: msbuild src/maui-cicd.sln -p:Configuration=Release

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts-windows
          path: |
            src\bin\Debug\**\*-Signed.apk
